services:
  postgresql:
    image: postgres
    container_name: postgres-purrweb
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
